# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            hwi
tagline:          'hwinareun'
description:      'study <a href="http://github.com/hwinareun" target="_blank">github</a> Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hwinareun.github.io
baseurl:          /

author:
  name:           'hwinareun'
  url:            http://hwinareun.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:           http://github.com/hwinareun
  repo:           http://github.com/hwinareun
